print("Robb's Online Username Generator.")
print("Let's start with something easy!")
favorite_tv_character = input("What is the first letter of the name of your favorite TV character?\n")
favorite_icecream_flavor = input("What is the second letter of your favorite ice cream flavor?\n")
pet_name = input("What is the third letter of your pet's name?\n")
print("No way! Mine too. That's so weird! Sorry. Let's continue.")
favorite_city = input("What is the forth letter of your favorite city?\n")
favorite_holiday = input("What is the fifth letter of your favorite holiday?\n")
print("This is getting spooky. We're in sync. This is amazing.")
my_daughter = input("What is the sixth letter of the word: Amelia?\n")
turkey_largest_city = input("What is the seventh letter of Turkey's largest city?\n")
print("Hmmmm. This is too much. Is this me from the future?")
jamaica_first_primeminister = input("What is the eighth letter of the first name of Jamaica's first prime minister?\n")
eight_largest_country = input("What is the ninth letter of the world's eighth largest country?\n")
print("I give up. You're like pyschic!")
combine_haiti_dominicanrepublic = input("What is the tenth letter of the name used when you combine Haiti and the Dominican Republic?\n")
print("Your online username should be: " + jamaica_first_primeminister+favorite_city+favorite_tv_character+favorite_holiday+favorite_icecream_flavor+my_daughter+turkey_largest_city+combine_haiti_dominicanrepublic+pet_name+eight_largest_country)
print("I think that's a dope username. Well done!")
